version: '2'

volumes:
  arxiv-data:
    external:
      name: sanity
  arxiv-info:
    external:
      name: info
  arxiv-thumbs:
    external:
      name: thumbs
  data:
    external:
      name: data2

services:
    arxiv-sanity:
        container_name: "arxiv-sanity"
        image: arxiv-sanity
        volumes:
            - arxiv-data:/arxiv/data
            - arxiv-info:/arxiv/info
            - arxiv-thumbs:/arxiv/static/thumbs
        ports:
            - 8080:8080
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - data:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
